--Напишите скрипт создания таблицы со следующими параметрами:
--название таблицы - CUSTOMERS
--содержит в себе 5 столбцов - id, name, surname, age, phone_number
--первичным ключом будет поле id, который инкрементируется каждый раз, при создании пользователя

create table homework.CUSTOMERS(
                                   id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                   name varchar,
                                   surname varchar,
                                   age int,
                                   phone_number varchar
);

insert into homework.customers ( name, surname, age, phone_number)
values ('Pavel','Pavlov', 35, '+79006005040'),
       ('Ivan', 'Ivanov', 34, '+7(3812)906050'),
       ('Petr', 'Petrov', 24, '+7(495)9005040'),
       ('Alexey','Alexeev', 35, '+79006005040');

